apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qj 
  janus-idp.io/tekton: qj
  backstage.io/kubernetes-id: qj
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qj
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  