apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: qj
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jduimovich0/qj:5cad3165b661190be98826c922f966990e2befc8@sha256:bbd91a4a6f7c63e4c6cb25e17839d9bc3be30468e93bb1d0a75fbe473c24bbe7
          name: container-image
